from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('stocks/', views.stocks, name='stocks'),
    path('real-estate/', views.real_estate, name='real_estate'),
    path('crypto/', views.crypto, name='crypto'),
    path('farmland/', views.farmland, name='farmland'),
    path('gold/', views.gold, name='gold'),
    path('treasury-bonds/', views.treasury_bonds, name='treasury_bonds'),
    path('sp500-pe-ratio/', views.sp500_pe_ratio, name='sp500_pe_ratio'),
    path('stocks-percentage/', views.stocks_percentage, name='stocks_percentage'),
    path('stocks-gdp/', views.stocks_gdp, name='stocks_gdp'),
    path('sp500-percentage/', views.sp500_percentage, name='sp500_percentage'),
    path('top20-percentage/', views.top20_percentage, name='top20_percentage'),
    path('stocks-pe-ratio/', views.stocks_pe_ratio, name='stocks_pe_ratio'),
    path('basic-materials-percentage/', views.basic_materials_percentage, name='basic_materials_percentage'),
    path('communication-services-percentage/', views.communication_services_percentage, name='communication_services_percentage'),
    path('consumer-cyclical-percentage/', views.consumer_cyclical_percentage, name='consumer_cyclical_percentage'),
    path('consumer-defensive-percentage/', views.consumer_defensive_percentage, name='consumer_defensive_percentage'),
    path('energy-percentage/', views.energy_percentage, name='energy_percentage'),
    path('financial-services-percentage/', views.financial_services_percentage, name='financial_services_percentage'),
    path('healthcare-percentage/', views.healthcare_percentage, name='healthcare_percentage'),
    path('industrials-percentage/', views.industrials_percentage, name='industrials_percentage'),
    path('real-estate-sector-percentage/', views.real_estate_sector_percentage, name='real_estate_sector_percentage'),
    path('technology-percentage/', views.technology_percentage, name='technology_percentage'),
    path('utilities-percentage/', views.utilities_percentage, name='utilities_percentage'),
    path('total-assets/', views.total_assets, name='total_assets'),
    path('gdp-chart/', views.gdp_chart, name='gdp_chart'),
    path('real-estate-percentage/', views.real_estate_percentage, name='real_estate_percentage'),
    path('real-estate-gdp/', views.real_estate_gdp, name='real_estate_gdp'),
    path('residential-real-estate-percentage/', views.residential_real_estate_percentage, name='residential_real_estate_percentage'),
    path('residential-real-estate-gdp/', views.residential_real_estate_gdp, name='residential_real_estate_gdp'),
    path('commercial-real-estate-percentage/', views.commercial_real_estate_percentage, name='commercial_real_estate_percentage'),
    path('commercial-real-estate-gdp/', views.commercial_real_estate_gdp, name='commercial_real_estate_gdp'),
    path('crypto-percentage/', views.crypto_percentage, name='crypto_percentage'),
    path('bitcoin-percentage/', views.bitcoin_percentage, name='bitcoin_percentage'),
    path('ethereum-percentage/', views.ethereum_percentage, name='ethereum_percentage'),
    path('other-crypto-percentage/', views.other_crypto_percentage, name='other_crypto_percentage'),
    path('gold-percentage/', views.gold_percentage, name='gold_percentage'),
    path('treasury-bonds-percentage/', views.treasury_bonds_percentage, name='treasury_bonds_percentage'),
] 